version: '2'
services:
  web:
    image: docker-libsumo
    ports:
      - "5000:5000"
    environment:
      - PYTHON
    volumes:UNBUFFERED=0

    depends_on:
      - redis
  redis:
    image: redis
